export const OFF_PLAN_LISTINGS = [
  {
    slug: "sobha-seahaven-tower-a",
    title: "Sobha Seahaven Tower A",
    types: "Apartments",
    developer: "Sobha Realty",
    location: "Dubai Harbour",
    startingPrice: "AED 4.20M",
    bedrooms: "2-3 BR",
    handover: "Q4 2026",
    tags: ["HIGH ROI", "EXCLUSIVE"],
    imageUrl: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&h=600&fit=crop&auto=format",
  },
  {
    slug: "emaar-creek-waters-2",
    title: "Creek Waters 2",
    types: "Apartments",
    developer: "Emaar",
    location: "Dubai Creek Harbour",
    startingPrice: "AED 2.40M",
    bedrooms: "1-3 BR",
    handover: "Q1 2027",
    tags: ["HIGH ROI", "FOR SALE"],
    imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop&auto=format",
  },
  {
    slug: "damac-lagoons-morocco",
    title: "Damac Lagoons Morocco",
    types: "Apartments, Penthouses, Duplexes",
    developer: "Damac",
    location: "Damac Hills 2",
    startingPrice: "AED 2.10M",
    bedrooms: "1-4 BR",
    handover: "Q2 2026",
    tags: ["HIGH ROI", "FOR SALE"],
    imageUrl: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&h=600&fit=crop&auto=format",
  },
  {
    slug: "ellington-views-i",
    title: "Ellington Views I",
    types: "Studios, Apartments",
    developer: "Ellington",
    location: "Motor City",
    startingPrice: "AED 1.20M",
    bedrooms: "Studio-2 BR",
    handover: "Q4 2026",
    tags: ["HIGH ROI"],
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop&auto=format",
  },
  {
    slug: "meraas-port-de-la-mer",
    title: "Port De La Mer",
    types: "Apartments, Serviced Apartments",
    developer: "Meraas",
    location: "La Mer, Jumeirah",
    startingPrice: "AED 4.20M",
    bedrooms: "1-4 BR",
    handover: "Q2 2026",
    tags: ["EXCLUSIVE"],
    imageUrl: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=600&fit=crop&auto=format",
  },
  {
    slug: "nakheel-manor",
    title: "Nakheel The Manor",
    types: "Villas, Townhouses",
    developer: "Nakheel",
    location: "Palm Jumeirah",
    startingPrice: "AED 12M",
    bedrooms: "4-6 BR",
    handover: "Q3 2027",
    tags: ["HIGH ROI", "EXCLUSIVE"],
    imageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop&auto=format",
  },
  {
    slug: "aldar-yas-park",
    title: "Aldar Yas Park Gate",
    types: "Apartments",
    developer: "Aldar",
    location: "Yas Island, Abu Dhabi",
    startingPrice: "AED 1.50M",
    bedrooms: "1-3 BR",
    handover: "Q1 2028",
    tags: ["HIGH ROI"],
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop&auto=format",
  },
  {
    slug: "binghatti-phoenix",
    title: "Binghatti Phoenix",
    types: "Studios, Apartments",
    developer: "Binghatti",
    location: "Jumeirah Village Circle",
    startingPrice: "AED 890K",
    bedrooms: "Studio-2 BR",
    handover: "Q4 2025",
    tags: ["FOR SALE"],
    imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=600&fit=crop&auto=format",
  },
];

export const TAG_STYLES: Record<string, string> = {
  "HIGH ROI":  "bg-emerald-500 text-white",
  "FOR SALE":  "bg-sky-500 text-white",
  "EXCLUSIVE": "bg-pg-gold text-white",
};

export const WHATSAPP_NUMBER = "971000000000";
